---
# Kali
- name: Provision Kali Linux
  hosts: kali
  become: yes  # Use sudo for privilege escalation
  tasks:

    # Update apt package index
    - name: Update apt package index
      apt:
        update_cache: yes

    # Install basic packages
    - name: Install basic packages
      apt:
        name:
          - metasploit-framework
          - nmap
          - nikto
          - burpsuite
          - hydra
          - tmux
          - git
          - nmap
          - metasploit-framework
          - python3-pip
        state: present

    - name: Clone SecLists repository
      git:
        repo: "https://github.com/danielmiessler/SecLists.git"
        dest: "/opt/SecLists"
        clone: yes
        update: yes

    - name: Install xrdp and xfce4
      apt:
        name:
          - xrdp
          - xfce4
          - xfce4-goodies
        state: present

    - name: Enable and start xrdp service
      systemd:
        name: xrdp
        enabled: yes
        state: started

    - name: Allow xrdp in UFW (if firewall is used)
      ufw:
        rule: allow
        port: "3389"
        proto: tcp
      ignore_errors: yes  # Ignore if UFW is not installed

    - name: Set XFCE4 as default session for RDP
      copy:
        dest: /home/vagrant/.xsession
        content: "xfce4-session"
        owner: vagrant
        group: vagrant
        mode: '0644'

    - name: Restart xrdp service
      systemd:
        name: xrdp
        state: restarted