---
# Kali
- name: Provision Kali Linux
  hosts: kali
  become: yes  # Use sudo for privilege escalation
  tasks:

    # Update apt package index
    - name: Update apt package index
      apt:
        update_cache: yes

    # Install basic packages
    - name: Install basic packages
      apt:
        name:
          - metasploit-framework
          - nmap
          - nikto
          - burpsuite
          - hydra
        state: present

    # # Placeholder: Install GitHub tools (add specific tools)
    # - name: Install tools from GitHub
    #   git:
    #     repo: "https://github.com/your/tool-repository.git"
    #     dest: "/home/kali/Desktop/tools/your-tool"
    #     clone: yes
    #     update: yes

    # # Placeholder: Example of installing a tool using a release tarball
    # - name: Download and install custom tool
    #   get_url:
    #     url: "https://github.com/your/custom-tool/releases/download/v1.0/tool.tar.gz"
    #     dest: "/home/kali/Desktop/tools/tool.tar.gz"

    # - name: Extract the tool
    #   unarchive:
    #     src: "/tmp/tool.tar.gz"
    #     dest: "/home/kali/Desktop/tools/"
    #     remote_src: yes

    # Install additional tools via apt or any other package manager
    - name: Install additional tools (example)
      apt:
        name: "your-package-name"
        state: present